services:
  db:
    image: postgres:15
    container_name: todo_db
    restart: always
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: todo_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: todo_user
      DB_PASSWORD: todo_pass
      DB_NAME: todo_db
      PORT: 3001
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: todo_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  pgdata:
  grafana-data:
  jenkins-data: